// --- [index.js]: This is the main entry point for this node.js application. ---

// [dotenv]: used for managing API key.
require('dotenv').config();

const express = require('express');
const path = require('path');
const cors = require('cors'); 
const { GoogleGenAI } = require('@google/genai');
const db = require('./postgreSQL-database');

// [rate limiter]: prevents the endpoint from being spammed more than the maximum allowed limit.
const rateLimit = require('express-rate-limit');
const limiter = rateLimit({
	windowMs: 15 * 60 * 1000, // 15 minutes
	max: 10 // limit each IP to 10 requests per window
});

// Initialize the Express application
const app = express();
app.use('/api/generate-music', limiter);

// Define the port the server will run on
const PORT = process.env.PORT || 3000;

// Enable CORS for all routes (i.e., allows the Canvas to talk to your localhost!)
app.use(cors());

// Middleware to parse incoming JSON requests
app.use(express.json({limit: '5mb'}));

// Serve static files (HTML, CSS, JS) from the 'public' directory
app.use(express.static(path.join(__dirname, 'public')));


// --- Generative AI (Google) ---

if (!process.env.GEMINI_API_KEY) {
    console.error("❌ CRITICAL ERROR: GEMINI_API_KEY is missing in .env file");
    process.exit(1); 
}

// Initialize the Gemini client using an API key
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// --- API Endpoints ---

app.get('/api/test', (request,response) => {
	response.json({
		success: true,
		timestamp: new Date().toISOString()
	})
})

app.post('/api/generate-music', async (req, res) => {
  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  try {
    console.log(`Sending prompt to Gemini API: "${prompt}"...`);

    // Call the Gemini API using the Lyria 3 music generation model
    const response = await ai.models.generateContent({
      model: 'lyria-3-clip-preview',  // 'lyria-3-clip-preview' for ~30s clips, 'lyria-3-pro-preview' for ~3min clips.
      contents: prompt,
      config: {
        responseModalities: ['AUDIO', 'TEXT'],
      },
    });

    // Extract the candidate from the response
    const candidate = response.candidates[0];

    // 1. Check if the AI was forced to stop due to safety filters
    if (candidate.finishReason && candidate.finishReason !== 'STOP') {
      console.warn(`⚠️ Generation blocked. Reason: ${candidate.finishReason}`);
      return res.status(400).json({ 
        error: `Music generation was blocked by safety filters. Reason: ${candidate.finishReason}` 
      });
    }

    // 2. Safely look for the audio part
    const audioPart = candidate.content?.parts?.find(part => part.inlineData);

    if (audioPart && audioPart.inlineData) {
      // The audio is returned as a base64 encoded string
      const audioBase64 = audioPart.inlineData.data;
      const audioBuffer = Buffer.from(audioBase64, 'base64');

	  // --- Save to PostgreSQL ---
      try {
        await db.query(
          'INSERT INTO generations (prompt, status) VALUES ($1, $2)',
          [prompt, 'SUCCESS']
        );
        console.log('✅ Generation saved to database!');
      } catch (dbError) {
        console.error('⚠️ Could not save to database, but audio generated:', dbError);
      }
      // -------------------------------

      // Send the raw MP3 audio file back to the client
      res.set('Content-Type', 'audio/mp3');
      res.send(audioBuffer);
    } else {
      res.status(500).json({ error: 'No audio generated by the model, but no safety filter was triggered.' });
    }

  } catch (error) {
    // Check if it's an API error with a specific message
    const errorMessage = error.response?.data?.error?.message || error.message;
  
    // Log a cleaner version to your terminal
    console.error(`❌ API Error (${error.status}): ${errorMessage}`);

    if (error.status === 429) {
      return res.status(429).json({ 
        error: 'Quota exceeded or Tier 1 required. Please check your Google AI Studio billing settings.' 
      });
    }

    res.status(500).json({ error: 'Failed to generate music due to a server error.' });
  }
});

app.get('/api/history', async (req, res) => {
  try {
    // Fetch the 10 most recent generations
    const result = await db.query('SELECT * FROM generations ORDER BY created_at DESC LIMIT 10');
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching history:', error);
    res.status(500).json({ error: 'Failed to fetch generation history' });
  }
});

// Catches if the user goes to a route that does not exist.
app.use((req, res) => {
    res.status(404).send("Sorry, that page doesn't exist!");
});

app.use((err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: "Something broke internally!" });
});

// Start the server and listen on the specified port
const server = app.listen(PORT, () => {
    console.log(`🚀 Server is up and running at http://localhost:${PORT}`);
    console.log(`🌐 Local frontend: http://localhost:${PORT}.`);
    console.log(`⚡ API Endpoint 1: http://localhost:${PORT}/api/test`);
    console.log(`⚡ API Endpoint 2: http://localhost:${PORT}/api/generate-music`);
});

// INCREASE TIMEOUTS: Wait up to 5 minutes for the music generation to complete
server.setTimeout(300000); 
server.keepAliveTimeout = 300000;
server.headersTimeout = 300000;
